meta_product_name: "Matthieu Perraut"
meta_title: "Matthieu Perraut - Objectif Route du Rhum 2022"
meta_description: "De la Mini Transat 2019 à la Route du Rhum 2022, embarquez avec Matthieu Perraut, jeune navigateur passionné de course au large"
# meta_image: "matthieu-perraut-mini-transat.jpg" # should exist in `app/assets/images/`
